import Link from "next/link";
import { ArrowDownLeft, ArrowRight, ArrowUpRight, BellRing, CalendarClock, CircleDollarSign, Plus, ReceiptText, ShieldCheck, TrendingUp, Wallet } from "lucide-react";
import { formatMoney } from "@/domain/money";
import { previewExpenses, previewFinancials, sampleTrend } from "@/lib/preview/fixtures";
import { MonthControl } from "@/components/preview/controls";
import { FinancialChart } from "@/components/preview/financial-chart";
import { ExpenseTable } from "@/components/preview/expense-table";

const colors = ["#135cf7", "#6f91f1", "#32aa97", "#edb35d", "#d7dff0"];
function money(value: number) { return formatMoney(value, "NGN").replace(/\.00$/, ""); }

export function PreviewDashboard({ role, month }: { role: "super_admin" | "secretary"; month: string }) {
  const secretary = role === "secretary";
  const href = (section: string) => `/preview?role=${role}&section=${section}&month=${month}`;
  if (secretary) return <><div className="page-heading"><div><p className="eyebrow">YOUR DAILY WORKSPACE</p><h1>A good day to stay on track.</h1><p>Keep your records up to date, one entry at a time.</p></div><MonthControl role={role} section="dashboard" month={month} /></div><div className="operational-welcome"><div><span className="badge">SECRETARY WORKSPACE</span><h2>Every little detail counts.</h2><p>Log the day’s expenses and keep your supporting notes together.</p></div><div className="operational-illustration" aria-hidden="true"><ReceiptText size={60} strokeWidth={1} /><span><ShieldCheck size={20} /></span></div></div><div className="quick-actions">{[{ section: "expenses", title: "General expense", text: "Office supplies and everyday costs", icon: ReceiptText }, { section: "salaries", title: "Salary payment", text: "A record of team payments", icon: Wallet }, { section: "transport", title: "Daily transportation", text: "Morning, evening, and extras", icon: ArrowRight }, { section: "bills", title: "Bill payment", text: "Utilities and subscriptions", icon: CalendarClock }].map(({ section, title, text, icon: Icon }) => <Link className="panel quick-action" key={section} href={href(section)}><Icon size={22} /><strong>{title}</strong><p>{text}</p><span>Open preview <ArrowUpRight size={15} /></span></Link>)}</div><section className="panel"><div className="panel-heading"><div><h2>Your recent submissions</h2><p>Sample entries submitted by Amara Okafor</p></div><Link className="text-link" href={href("expenses")}>View all <ArrowRight size={15} /></Link></div><ExpenseTable rows={previewExpenses(month, true)} compact /></section><div className="submission-note"><ShieldCheck size={18} /><p>Your submitted records are final. Contact your Super Admin if a correction is needed.</p></div></>;
  const { summary, breakdown, sources } = previewFinancials(month);
  const hasData = breakdown.length > 0;
  const totalMajor = summary.totalExpensesMinor / 100;
  let start = 0;
  const stops = breakdown.map((item, i) => { const end = start + item.value / totalMajor * 100; const stop = `${colors[i]} ${start}% ${end}%`; start = end; return stop; });
  const trend = month === "2026-09" ? sampleTrend : month === "2026-08" ? sampleTrend.slice(0, -1) : [];
  const metrics = [
    { title: "Total revenue", value: summary.totalRevenueMinor, icon: ArrowDownLeft, tone: "blue", note: "Income earned this month" },
    { title: "Total expenses", value: summary.totalExpensesMinor, icon: ArrowUpRight, tone: "amber", note: "All paid expense categories" },
    { title: "Net profit", value: summary.netProfitMinor, icon: TrendingUp, tone: "green", note: "Revenue less expenses" },
    { title: "Closing balance", value: summary.closingBalanceMinor, icon: Wallet, tone: "purple", note: "Opening funds + net profit" },
  ];
  return <><div className="page-heading"><div><p className="eyebrow">THE BIG PICTURE</p><h1>Financial overview<span className="heading-period">.</span></h1><p>A clear view of what comes in, what goes out, and what’s ahead.</p></div><div className="heading-actions"><MonthControl role={role} section="dashboard" month={month} /><Link className="button primary" href={href("expenses")}><Plus size={17} /> Explore expenses</Link></div></div>
    <div className="fund-strip"><span className="fund-icon"><Wallet size={20} /></span><div><span>Monthly opening fund</span><strong>{hasData ? money(summary.openingFundMinor) : "Not set"}</strong></div><span className="fund-divider" /><div><span>Remaining opening fund</span><strong>{hasData ? money(summary.remainingOpeningFundMinor) : "—"}</strong></div><div className="fund-strip-right"><span className="badge subtle">NGN · Nigerian Naira</span><Link href={href("monthly-funds")} aria-label="View monthly funds"><ArrowUpRight size={18} /></Link></div></div>
    <div className="metrics-grid">{metrics.map(({ title, value, icon: Icon, tone, note }) => <section className={`panel metric-card ${tone}`} key={title}><div className="metric-top"><p>{title}</p><span className="metric-icon"><Icon size={18} /></span></div><strong className="metric-value">{money(value)}</strong><div className="metric-bottom"><span>{note}</span>{title === "Net profit" && <span className="metric-margin">{summary.profitMarginPercent === null ? "N/A" : `${summary.profitMarginPercent.toFixed(1)}%`} margin</span>}</div></section>)}</div>
    <div className="charts-grid"><section className="panel trend-panel"><div className="panel-heading"><div><h2>Money in. Money out.</h2><p>Revenue, expenses, and profit over time</p></div><span className="badge neutral">Sample trend · NGN</span></div>{trend.length ? <FinancialChart data={trend} /> : <div className="chart-empty">No sample trend for this month.</div>}</section><section className="panel breakdown-panel"><div className="panel-heading"><div><h2>Where it went</h2><p>Expense breakdown</p></div><ReceiptText className="muted" size={18} /></div><div className="donut-wrap"><div className="donut" role="img" aria-label="Expense category proportions, values listed below" style={{ background: hasData ? `conic-gradient(${stops.join(",")})` : "#edf0f5" }}><div><small>Total spent</small><strong>{hasData ? `₦${(totalMajor / 1000000).toFixed(2)}m` : "₦0"}</strong></div></div></div><ul className="breakdown-list">{breakdown.map((item, i) => <li key={item.name}><span><i style={{ background: colors[i] }} />{item.name}</span><strong>{money(item.value * 100)}</strong><small>{Math.round(item.value / totalMajor * 100)}%</small></li>)}</ul>{!hasData && <p className="center muted">No sample expenses to display.</p>}</section></div>
    <div className="details-grid"><section className="panel"><div className="panel-heading"><div><h2>Revenue by source</h2><p>What’s driving your income this month</p></div><CircleDollarSign className="muted" size={19} /></div><div className="source-list">{sources.map((source, i) => <div className="source-row" key={source.name}><span className={`source-icon source-${i}`}>{["DA", "CO", "CS"][i]}</span><div><div className="source-label"><strong>{source.name}</strong>{i === 0 && <span className="badge success">Top source</span>}<b>{money(source.amountMinor)}</b></div><div className="source-track"><span style={{ width: `${source.amountMinor / summary.totalRevenueMinor * 100}%`, background: colors[i] }} /></div></div></div>)}{!sources.length && <p className="muted">No sample revenue this month.</p>}</div></section><section className="panel upcoming-panel"><div className="panel-heading"><div><h2>Coming up</h2><p>Sample reminders · September 2026</p></div><BellRing className="muted" size={18} /></div><div className="bill-list">{[{ day: "10", title: "Workspace subscription", amount: 85000, tag: "Due in 3 days", tone: "warning" }, { day: "14", title: "Office electricity", amount: 62000, tag: "Due in 7 days", tone: "neutral" }, { day: "18", title: "Cloud services", amount: 48000, tag: "Due in 11 days", tone: "neutral" }].map((bill) => <div className="bill-row" key={bill.title}><div className="bill-date"><small>SEP</small><strong>{bill.day}</strong></div><div><strong>{bill.title}</strong><span className={`bill-status ${bill.tone}`}>{bill.tag}</span></div><b>{money(bill.amount * 100)}</b></div>)}</div><Link className="panel-bottom-link" href={href("bills")}>View all bills <ArrowRight size={15} /></Link></section></div>
    <section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent expenses</h2><p>Illustrative register entries · separate from the summary dataset</p></div><Link className="text-link" href={href("expenses")}>View all expenses <ArrowRight size={15} /></Link></div><ExpenseTable rows={previewExpenses(month, false)} compact /></section>
    <p className="preview-footnote">All figures are fictional design examples. “Coming up” uses 7 September 2026 as its reference date.</p>
  </>;
}
